package review2.GUI;

import javax.swing.JOptionPane;

/**
 *
 * @author WaLiD
 */
public class JavaReviewFrame extends javax.swing.JFrame {

    /**
     * Creates new form JavaReviewFrame
     */
    public JavaReviewFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        majorButtonGroup = new javax.swing.ButtonGroup();
        areaButtonGroup = new javax.swing.ButtonGroup();
        formLabel = new javax.swing.JLabel();
        namejLabel = new javax.swing.JLabel();
        nameTxtBx = new javax.swing.JTextField();
        majorJLabel = new javax.swing.JLabel();
        astRadioButton = new javax.swing.JRadioButton();
        btRadioButton = new javax.swing.JRadioButton();
        submitjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        creditTextField = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        nyRadioButton = new javax.swing.JRadioButton();
        outStateRadioButton = new javax.swing.JRadioButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formLabel.setText("Semester Fee Calculator ");

        namejLabel.setText("name:");

        majorJLabel.setText("Major:");

        majorButtonGroup.add(astRadioButton);
        astRadioButton.setText("AAS");
        astRadioButton.setToolTipText("");
        astRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                astRadioButtonActionPerformed(evt);
            }
        });

        majorButtonGroup.add(btRadioButton);
        btRadioButton.setText("BT");

        submitjButton.setText("Submit");
        submitjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                submitjButtonActionPerformed(evt);
            }
        });

        jLabel1.setText("Credit Taken:");

        creditTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                creditTextFieldActionPerformed(evt);
            }
        });

        jLabel2.setText("Area:");

        areaButtonGroup.add(nyRadioButton);
        nyRadioButton.setText("New York");
        nyRadioButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyRadioButtonActionPerformed(evt);
            }
        });

        areaButtonGroup.add(outStateRadioButton);
        outStateRadioButton.setText("Out of State");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(namejLabel)
                    .addComponent(majorJLabel))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(astRadioButton)
                            .addComponent(nameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(formLabel)
                            .addComponent(creditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(nyRadioButton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(outStateRadioButton))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(submitjButton)
                            .addComponent(btRadioButton))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(formLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(namejLabel)
                    .addComponent(nameTxtBx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(astRadioButton)
                    .addComponent(btRadioButton)
                    .addComponent(majorJLabel))
                .addGap(25, 25, 25)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(creditTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(nyRadioButton)
                    .addComponent(outStateRadioButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addComponent(submitjButton)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void astRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_astRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_astRadioButtonActionPerformed

    private void submitjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_submitjButtonActionPerformed

        String status;
        double tution = 0;
        double credit = 0;
        String name = nameTxtBx.getText();
        String creditStatus = null;

        //checking the major of a student 
        if (astRadioButton.isSelected()) {
            status = astRadioButton.getText();
        } else {
            status = btRadioButton.getText();
        }

        //chekcing the credit and tution fee of the student
        credit = Double.parseDouble(creditTextField.getText());

        //checking if the student part-time or full time
        if (credit > 0 && credit < 12) {

            if (nyRadioButton.isSelected()) {
                tution = credit * 275;
                creditStatus = "You are part-time student"
                        + "\n Area: " + nyRadioButton.getText()
                        + "\nYour tution fee 275/credit";
            } else {
                tution = credit * 560;
                creditStatus = "You are part-time student"
                        + "\n Area: " + outStateRadioButton.getText()
                        + "\nYour tution fee 560/credit";
            }

        } else if (credit > 0 && credit < 22) { //if the student full time 

            if (nyRadioButton.isSelected()) {
                tution = credit * 210;
                creditStatus = "You are full-time student"
                        + "\n Area: " + nyRadioButton.getText()
                        + "\nYour tution fee 210/credit";
            } else {
                tution = credit * 320;
                creditStatus = "You are part-time student"
                        + "\n Area: " + outStateRadioButton.getText()
                        + "\nYour tution fee 320/credit";
            }

        } else {
            if(credit < 1 ){
                creditStatus = "it's an invalid credit numer";
            }else{
                creditStatus = "You can not take more than 22 credits";
            }    
            
        }

        // Display the charges.
        JOptionPane.showMessageDialog(null, "Name: " + name
                + "\n Semester Status: " + status
                + "\n Credit taken: " + credit
                + "\n"+ creditStatus
                + "\n Tution fee for the semester: $" + tution);

    }//GEN-LAST:event_submitjButtonActionPerformed

    private void creditTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_creditTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_creditTextFieldActionPerformed

    private void nyRadioButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyRadioButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nyRadioButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaReviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaReviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaReviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaReviewFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaReviewFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup areaButtonGroup;
    private javax.swing.JRadioButton astRadioButton;
    private javax.swing.JRadioButton btRadioButton;
    private javax.swing.JTextField creditTextField;
    private javax.swing.JLabel formLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.ButtonGroup majorButtonGroup;
    private javax.swing.JLabel majorJLabel;
    private javax.swing.JTextField nameTxtBx;
    private javax.swing.JLabel namejLabel;
    private javax.swing.JRadioButton nyRadioButton;
    private javax.swing.JRadioButton outStateRadioButton;
    private javax.swing.JButton submitjButton;
    // End of variables declaration//GEN-END:variables
}
